// Keycode display labels map
        const DISPLAY_MAP = {
            K_TRNS: "▽",
            K_NO: "✕",
            K_A: "A", K_B: "B", K_C: "C", K_D: "D", K_E: "E", K_F: "F", K_G: "G",
            K_H: "H", K_I: "I", K_J: "J", K_K: "K", K_L: "L", K_M: "M", K_N: "N",
            K_O: "O", K_P: "P", K_Q: "Q", K_R: "R", K_S: "S", K_T: "T", K_U: "U",
            K_V: "V", K_W: "W", K_X: "X", K_Y: "Y", K_Z: "Z",
            K_1: "1", K_2: "2", K_3: "3", K_4: "4", K_5: "5",
            K_6: "6", K_7: "7", K_8: "8", K_9: "9", K_0: "0",
            K_ESC: "ESC",
            K_TAB: "↹",
            K_SPC: "␣",
            K_ENT: "↵",
            K_BSPC: "⌫",
            K_MINS: "-",
            K_EQL: "=",
            K_LBRC: "[",
            K_RBRC: "]",
            K_BSLS: "\\",
            K_SCLN: ";",
            K_QUOT: "'",
            K_GRV: "`",
            K_COMM: ",",
            K_DOT: ".",
            K_SLSH: "/",
            K_CAPS: "CAPS",
            K_LCTRL: "LCTRL",
            K_RCTRL: "RCTRL",
            MOD_LCTRL: "LCTRL",
            MOD_RCTRL: "RCTRL",
            K_LSHIFT: "LSHIFT",
            K_RSHIFT: "RSHIFT",
            MOD_LSHIFT: "LSHIFT",
            MOD_RSHIFT: "RSHIFT",
            K_LALT: "LALT",
            K_RALT: "RALT",
            MOD_LALT: "LALT",
            MOD_RALT: "RALT",
            K_LGUI: "LGUI",
            K_RGUI: "RGUI",
            MOD_LGUI: "LGUI",
            MOD_RGUI: "RGUI",
            MOD_HYPER: "HYP",
            K_LEFT: "←",
            K_RIGHT: "→",
            K_UP: "↑",
            K_DOWN: "↓",
            K_INS: "INS",
            K_DEL: "DEL",
            K_HOME: "HOME",
            K_END: "END",
            K_PGUP: "PGUP",
            K_PGDN: "PGDN",
            K_PSCR: "PRTSC",
            K_SCRL: "SCRLK",
            K_PAUS: "PAUSE",
            K_MENU: "MENU",
            // F1 - F24 generated dynamically below
            K_EXECUTE: "EXEC",
            K_HELP: "HELP",
            K_MENU_KB: "MENU",
            K_SELECT: "SEL",
            K_STOP_KB: "STOP",
            K_AGAIN: "AGAIN",
            K_UNDO: "UNDO",
            K_CUT: "CUT",
            K_COPY: "COPY",
            K_PASTE: "PASTE",
            K_FIND: "FIND",
            K_NLCK: "NUM",
            K_KP_SLASH: "NUM /",
            K_KP_ASTERISK: "NUM *",
            K_KP_MINUS: "NUM -",
            K_KP_PLUS: "NUM +",
            K_KP_ENTER: "NUM ↵",
            K_KP_DOT: "NUM .",
            K_KP_EQUAL: "NUM =",
            // K_KP0 - K_KP9 generated dynamically below
            K_MUTE: "MUTE",
            K_VOLU: "VOL+",
            K_VOLD: "VOL-",
            K_MPLY: "PLAY",
            K_MNXT: "NEXT",
            K_MPRV: "PREV",
            K_MSTP: "STOP",
            K_BRIU: "BRI+",
            K_BRID: "BRI-",
            K_CALC: "CALC",
            K_MYCM: "PC",
            K_MAIL: "MAIL",
            K_WSCH: "FIND",
            K_WHOM: "HOME",
            K_WBAK: "BACK",
            K_WFWD: "FWD",
            K_WSTP: "STOP",
            K_WREF: "REFR",
            K_WFAV: "FAV",
            K_MFFD: "FFWD",
            K_MRWD: "RWND",
            K_EJCT: "EJCT",
            K_MSEL: "MSEL",
            // RGB Controls
            RGB_TOGG: "RGB TOG",
            RGB_NEXT: "RGB NEXT",
            RGB_PREV: "RGB PREV",
            RGB_HUI: "HUE +",
            RGB_HUD: "HUE -",
            RGB_SAI: "SAT +",
            RGB_SAD: "SAT -",
            RGB_VAI: "BRI +",
            RGB_VAD: "BRI -",
            RGB_SPI: "SPD +",
            RGB_SPD: "SPD -",
            // Mouse Keys
            K_MS_UP: "MS ↑",
            K_MS_DOWN: "MS ↓",
            K_MS_LEFT: "MS ←",
            K_MS_RIGHT: "MS →",
            K_MS_BTN1: "MS L",
            K_MS_BTN2: "MS R",
            K_MS_BTN3: "MS M",
            K_MS_BTN4: "MS 4",
            K_MS_BTN5: "MS 5",
            K_MS_WH_UP: "WH ↑",
            K_MS_WH_DOWN: "WH ↓",
            K_MS_WH_LEFT: "WH ←",
            K_MS_WH_RIGHT: "WH →",
            K_MS_ACCEL0: "ACL 0",
            K_MS_ACCEL1: "ACL 1",
            K_MS_ACCEL2: "ACL 2",
            // Gamepad Buttons (GP_BTN1 - GP_BTN32 generated dynamically below)
            GP_A: "GP A", GP_B: "GP B", GP_X: "GP X", GP_Y: "GP Y",
            GP_LB: "GP LB", GP_RB: "GP RB", GP_LT: "GP LT", GP_RT: "GP RT",
            GP_SELECT: "SELECT", GP_START: "START",
            GP_L3: "GP L3", GP_R3: "GP R3",
            GP_DPAD_UP: "DPAD ↑", GP_DPAD_DOWN: "DPAD ↓", GP_DPAD_LEFT: "DPAD ←", GP_DPAD_RIGHT: "DPAD →",
            GP_LX_LEFT: "LX ←", GP_LX_RIGHT: "LX →", GP_LY_UP: "LY ↑", GP_LY_DOWN: "LY ↓",
            GP_RX_LEFT: "RX ←", GP_RX_RIGHT: "RX →", GP_RY_UP: "RY ↑", GP_RY_DOWN: "RY ↓",
            // MIDI Controls
            MIDI_OCTAVE_DOWN: "OCT -", MIDI_OCTAVE_UP: "OCT +",
            MIDI_TRANSPOSE_DOWN: "TRN -", MIDI_TRANSPOSE_UP: "TRN +",
            MIDI_VELOCITY_DOWN: "VEL -", MIDI_VELOCITY_UP: "VEL +",
            MIDI_CHANNEL_DOWN: "CH -", MIDI_CHANNEL_UP: "CH +",
            MIDI_ALL_NOTES_OFF: "PANIC",
            MIDI_SUSTAIN: "SUSTAIN", MIDI_PORTAMENTO: "PORT", MIDI_SOSTENUTO: "SOST",
            MIDI_SOFT: "SOFT", MIDI_LEGATO: "LEGATO", MIDI_MODULATION: "MOD",
            MIDI_PITCH_BEND_DOWN: "PB -", MIDI_PITCH_BEND_UP: "PB +",
            "CC X": "CC X",
            "CC(...)": "CC X",
            "CC_TOG(...)": "CC TOG",
            "CC_VAL127(...)": "CC ON",
            "CC_VAL0(...)": "CC OFF",
            "CC_INC(...)": "CC +",
            "CC_DEC(...)": "CC -",
            // International / ISO
            K_NONUS_HASH: "# ~",
            K_NONUS_BSLASH: "\\ |",
            K_KP_COMMA: "NUM ,",
            K_KP_EQUAL_AS400: "NUM =",
            K_LOCKING_CAPS: "LCAPS",
            K_LOCKING_NUM: "LNUM",
            K_LOCKING_SCROLL: "LSCRL",
            K_LYRUP: "LAYER ▲",
            K_LYRDWN: "LAYER ▼",
            K_BOOTLOADER: "BOOT"
        };

        // Generators for repetitive keycode labels (reducing dictionary bloat)
        for (let i = 1; i <= 24; i++) DISPLAY_MAP[`K_F${i}`] = `F${i}`;
        for (let i = 0; i <= 9; i++) DISPLAY_MAP[`K_KP${i}`] = `N${i}`;
        for (let i = 1; i <= 32; i++) DISPLAY_MAP[`GP_BTN${i}`] = `GP ${i}`;
        for (let i = 1; i <= 9; i++) {
            DISPLAY_MAP[`K_INT${i}`] = `INT ${i}`;
            DISPLAY_MAP[`K_LANG${i}`] = `LANG${i}`;
        }
        const MIDI_NOTE_NAMES_SHORT = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
        const MIDI_NOTE_NAMES_CODE = ["C", "C_SHARP", "D", "D_SHARP", "E", "F", "F_SHARP", "G", "G_SHARP", "A", "A_SHARP", "B"];
        for (let oct = 0; oct <= 5; oct++) {
            for (let n = 0; n < 12; n++) {
                DISPLAY_MAP[`MIDI_NOTE_${MIDI_NOTE_NAMES_CODE[n]}_${oct}`] = `${MIDI_NOTE_NAMES_SHORT[n]}${oct}`;
            }
        }
        window.DISPLAY_MAP = DISPLAY_MAP;
