// Словарь для отображения знаков на кнопках (маппинг)
const DISPLAY_MAP = {
  // Базовые и прозрачность
  K_TRNS: "▽",
  K_NO: "✕",
  K_NULL: "✕",

  // Алфавит и цифры
  K_A: "A",
  K_B: "B",
  K_C: "C",
  K_D: "D",
  K_E: "E",
  K_F: "F",
  K_G: "G",
  K_H: "H",
  K_I: "I",
  K_J: "J",
  K_K: "K",
  K_L: "L",
  K_M: "M",
  K_N: "N",
  K_O: "O",
  K_P: "P",
  K_Q: "Q",
  K_R: "R",
  K_S: "S",
  K_T: "T",
  K_U: "U",
  K_V: "V",
  K_W: "W",
  K_X: "X",
  K_Y: "Y",
  K_Z: "Z",
  K_1: "1",
  K_2: "2",
  K_3: "3",
  K_4: "4",
  K_5: "5",
  K_6: "6",
  K_7: "7",
  K_8: "8",
  K_9: "9",
  K_0: "0",

  // Пунктуация и системные
  K_ESC: "ESC",
  K_TAB: "↹",
  K_SPC: "␣",
  K_ENT: "↵",
  K_BSPC: "⌫",
  K_MIN: "-",
  K_MINS: "-",
  K_EQU: "=",
  K_EQL: "=",
  K_BRAL: "[",
  K_LBRACKET: "[",
  K_LBRC: "[",
  K_BRAR: "]",
  K_RBRACKET: "]",
  K_RBRC: "]",
  K_BKSL: "\\",
  K_BSLASH: "\\",
  K_BSLS: "\\",
  K_SCLN: ";",
  K_SCOLON: ";",
  K_APOS: "'",
  K_QUOTE: "'",
  K_QUOT: "'",
  K_GRAV: "`",
  K_GRV: "`",
  K_COMM: ",",
  K_DOT: ".",
  K_SLSH: "/",
  K_HASH: "#",
  K_NONUS_HASH: "#",
  K_NUHS: "#",
  K_NONUS_BSLASH: "\\",
  K_NUBS: "\\",
  K_CAPS: "CAPS",
  K_CAPSLOCK: "CAPS",
  K_LOCKING_CAPS: "LCAP",
  K_LOCKING_NUM: "LNUM",
  K_LOCKING_SCROLL: "LSCR",

  // Модификаторы
  K_LCTL: "LCTRL",
  K_RCTL: "RCTRL",
  MOD_LCTRL: "LCTRL",
  MOD_RCTRL: "RCTRL",
  K_CTRL: "CTRL",
  K_LSFT: "LSHIFT",
  K_RSFT: "RSHIFT",
  MOD_LSHIFT: "LSHIFT",
  MOD_RSHIFT: "RSHIFT",
  K_SHFT: "SHIFT",
  K_LALT: "LALT",
  K_RALT: "RALT",
  MOD_LALT: "LALT",
  MOD_RALT: "RALT",
  K_ALT: "ALT",
  K_LGUI: "LGUI",
  K_RGUI: "RGUI",
  MOD_LGUI: "LGUI",
  MOD_RGUI: "RGUI",
  MOD_HYPER: "HYP",

  // Навигация, редактирование и F-кнопки
  K_A_L: "←",
  K_LEFT: "←",
  K_A_R: "→",
  K_RIGHT: "→",
  K_RGHT: "→",
  K_A_U: "↑",
  K_UP: "↑",
  K_A_D: "↓",
  K_DOWN: "↓",
  K_INS: "INS",
  K_INSERT: "INS",
  K_DEL: "DEL",
  K_DELETE: "DEL",
  K_HOME: "HOME",
  K_END: "END",
  K_PGUP: "PGUP",
  K_PAGE_UP: "PGUP",
  K_PGDN: "PGDN",
  K_PAGE_DOWN: "PGDN",
  K_PSCR: "PRTSC",
  K_PSCREEN: "PRTSC",
  K_SLCK: "SCRLK",
  K_SCKLOCK: "SCRLK",
  K_PAUS: "PAUSE",
  K_PAUSE: "PAUSE",
  K_APP: "APP",
  K_MENU: "MENU",
  K_APPLICATION: "APP",
  K_F1: "F1",
  K_F2: "F2",
  K_F3: "F3",
  K_F4: "F4",
  K_F5: "F5",
  K_F6: "F6",
  K_F7: "F7",
  K_F8: "F8",
  K_F9: "F9",
  K_F10: "F10",
  K_F11: "F11",
  K_F12: "F12",
  K_F13: "F13",
  K_F14: "F14",
  K_F15: "F15",
  K_F16: "F16",
  K_F17: "F17",
  K_F18: "F18",
  K_F19: "F19",
  K_F20: "F20",
  K_F21: "F21",
  K_F22: "F22",
  K_F23: "F23",
  K_F24: "F24",
  K_EXECUTE: "EXEC",
  K_HELP: "HELP",
  K_MENU_KB: "MENU",
  K_SELECT: "SEL",
  K_STOP_KB: "STOP",
  K_AGAIN: "AGAIN",
  K_UNDO: "UNDO",
  K_CUT: "CUT",
  K_COPY: "COPY",
  K_PASTE: "PASTE",
  K_FIND: "FIND",

  // Numpad
  K_NLCK: "NUM",
  K_NUMLOCK: "NUM",
  K_KPSL: "NUM /",
  K_KP_SLASH: "NUM /",
  K_PSLS: "NUM /",
  K_KPAX: "NUM *",
  K_KP_ASTERISK: "NUM *",
  K_PAST: "NUM *",
  K_KPMI: "NUM -",
  K_KP_MINUS: "NUM -",
  K_PMNS: "NUM -",
  K_KPPL: "NUM +",
  K_KP_PLUS: "NUM +",
  K_PPLS: "NUM +",
  K_KPEN: "NUM ↵",
  K_KP_ENTER: "NUM ↵",
  K_PENT: "NUM ↵",
  K_KPDT: "NUM .",
  K_KP_DOT: "NUM .",
  K_PDOT: "NUM .",
  K_KP_COMMA: "NUM ,",
  K_PCMM: "NUM ,",
  K_KP_EQUAL_AS400: "NUM =",
  K_KP_EQUAL: "NUM =",
  K_PEQL: "NUM =",
  K_KP0: "N0",
  K_KP1: "N1",
  K_KP2: "N2",
  K_KP3: "N3",
  K_KP4: "N4",
  K_KP5: "N5",
  K_KP6: "N6",
  K_KP7: "N7",
  K_KP8: "N8",
  K_KP9: "N9",
  K_P0: "N0",
  K_P1: "N1",
  K_P2: "N2",
  K_P3: "N3",
  K_P4: "N4",
  K_P5: "N5",
  K_P6: "N6",
  K_P7: "N7",
  K_P8: "N8",
  K_P9: "N9",

  // International & Language Keys
  K_INT1: "INT1",
  K_RO: "INT1",
  K_INT2: "INT2",
  K_KANA: "INT2",
  K_INT3: "INT3",
  K_JYEN: "INT3",
  K_INT4: "INT4",
  K_HENK: "INT4",
  K_INT5: "INT5",
  K_MHEN: "INT5",
  K_INT6: "INT6",
  K_INT7: "INT7",
  K_INT8: "INT8",
  K_INT9: "INT9",
  K_LANG1: "LNG1",
  K_LANG2: "LNG2",
  K_LANG3: "LNG3",
  K_LANG4: "LNG4",
  K_LANG5: "LNG5",
  K_LANG6: "LNG6",
  K_LANG7: "LNG7",
  K_LANG8: "LNG8",
  K_LANG9: "LNG9",

  // System Control & Power Keys
  K_POWER: "PWR",
  K_SYSTEM_POWER: "SYS PWR",
  K_PWR: "SYS PWR",
  K_SYSTEM_SLEEP: "SLEEP",
  K_SLEP: "SLEEP",
  K_SYSTEM_WAKE: "WAKE",
  K_WAKE: "WAKE",
  K_ROLL_OVER: "ROLL",
  K_POST_FAIL: "FAIL",
  K_UNDEFINED: "UNDEF",

  // Consumer Media Keys
  K_MUTE: "MUTE",
  K_AUDIO_MUTE: "MUTE",
  K_VOLU: "VOL+",
  K_AUDIO_VOL_UP: "VOL+",
  K_VOLD: "VOL-",
  K_AUDIO_VOL_DOWN: "VOL-",
  K_PLAY: "PLAY",
  K_MEDIA_PLAY_PAUSE: "PLAY",
  K_NEXT: "NEXT",
  K_MEDIA_NEXT_TRACK: "NEXT",
  K_PREV: "PREV",
  K_MEDIA_PREV_TRACK: "PREV",
  K_MSTP: "STOP",
  K_MEDIA_STOP: "STOP",
  K_MFFD: "FFWD",
  K_MEDIA_FAST_FORWARD: "FFWD",
  K_MRWD: "RWD",
  K_MEDIA_REWIND: "RWD",
  K_EJCT: "EJECT",
  K_MEDIA_EJECT: "EJECT",
  K_MSEL: "MSEL",
  K_MEDIA_SELECT: "MSEL",
  K_MAIL: "MAIL",
  K_CALC: "CALC",
  K_CALCULATOR: "CALC",
  K_MYCM: "PC",
  K_MY_COMPUTER: "PC",
  K_WSCH: "WEB🔍",
  K_WWW_SEARCH: "WEB🔍",
  K_WHOM: "WEB⌂",
  K_WWW_HOME: "WEB⌂",
  K_WBAK: "WEB←",
  K_WWW_BACK: "WEB←",
  K_WFWD: "WEB→",
  K_WWW_FORWARD: "WEB→",
  K_WSTP: "WEB✕",
  K_WWW_STOP: "WEB✕",
  K_WREF: "WEB↻",
  K_WWW_REFRESH: "WEB↻",
  K_WFAV: "WEB★",
  K_WWW_FAVORITES: "WEB★",
  K__MUTE: "KMUTE",
  K__VOLUP: "KVOL+",
  K__VOLDOWN: "KVOL-",

  // Virtual Mousekeys
  K_MS_UP: "M↑",
  K_MS_U: "M↑",
  K_MS_DOWN: "M↓",
  K_MS_D: "M↓",
  K_MS_LEFT: "M←",
  K_MS_L: "M←",
  K_MS_RIGHT: "M→",
  K_MS_R: "M→",
  K_MS_BTN1: "MB1",
  K_BTN1: "MB1",
  K_MS_BTN2: "MB2",
  K_BTN2: "MB2",
  K_MS_BTN3: "MB3",
  K_BTN3: "MB3",
  K_MS_BTN4: "MB4",
  K_BTN4: "MB4",
  K_MS_BTN5: "MB5",
  K_BTN5: "MB5",
  K_MS_WH_UP: "MW↑",
  K_WH_U: "MW↑",
  K_MS_WH_DOWN: "MW↓",
  K_WH_D: "MW↓",
  K_MS_WH_LEFT: "MW←",
  K_WH_L: "MW←",
  K_MS_WH_RIGHT: "MW→",
  K_WH_R: "MW→",
  K_MS_ACCEL0: "ACL0",
  K_ACL0: "ACL0",
  K_MS_ACCEL1: "ACL1",
  K_ACL1: "ACL1",
  K_MS_ACCEL2: "ACL2",
  K_ACL2: "ACL2",

  // Custom Layer & System Keys
  K_LYRUP: "LYR↑",
  K_LYRDWN: "LYR↓",
};

// Полный список всех уникальных алиасов для палитры
const PALETTE_CODES = [
  // Базовые
  "K_TRNS",
  "K_NO",
  "K_NULL",

  // Алфавит и цифры
  "K_A",
  "K_B",
  "K_C",
  "K_D",
  "K_E",
  "K_F",
  "K_G",
  "K_H",
  "K_I",
  "K_J",
  "K_K",
  "K_L",
  "K_M",
  "K_N",
  "K_O",
  "K_P",
  "K_Q",
  "K_R",
  "K_S",
  "K_T",
  "K_U",
  "K_V",
  "K_W",
  "K_X",
  "K_Y",
  "K_Z",
  "K_1",
  "K_2",
  "K_3",
  "K_4",
  "K_5",
  "K_6",
  "K_7",
  "K_8",
  "K_9",
  "K_0",

  // Пунктуация
  "K_ESC",
  "K_TAB",
  "K_SPC",
  "K_ENT",
  "K_BSPC",
  "K_MIN",
  "K_EQU",
  "K_BRAL",
  "K_BRAR",
  "K_BKSL",
  "K_SCLN",
  "K_APOS",
  "K_GRAV",
  "K_COMM",
  "K_DOT",
  "K_SLSH",
  "K_HASH",
  "K_NUBS",
  "K_CAPS",

  // Модификаторы
  "K_LCTL",
  "K_LSFT",
  "K_LALT",
  "K_LGUI",
  "K_RCTL",
  "K_RSFT",
  "K_RALT",
  "K_RGUI",
  "K_LOCKING_CAPS",
  "K_LOCKING_NUM",
  "K_LOCKING_SCROLL",

  // Навигация и F-кнопки
  "K_A_L",
  "K_A_R",
  "K_A_U",
  "K_A_D",
  "K_INS",
  "K_DEL",
  "K_HOME",
  "K_END",
  "K_PGUP",
  "K_PGDN",
  "K_PSCR",
  "K_SLCK",
  "K_PAUS",
  "K_APP",
  "K_F1",
  "K_F2",
  "K_F3",
  "K_F4",
  "K_F5",
  "K_F6",
  "K_F7",
  "K_F8",
  "K_F9",
  "K_F10",
  "K_F11",
  "K_F12",
  "K_F13",
  "K_F14",
  "K_F15",
  "K_F16",
  "K_F17",
  "K_F18",
  "K_F19",
  "K_F20",
  "K_F21",
  "K_F22",
  "K_F23",
  "K_F24",
  "K_EXECUTE",
  "K_HELP",
  "K_MENU_KB",
  "K_SELECT",
  "K_STOP_KB",
  "K_AGAIN",
  "K_UNDO",
  "K_CUT",
  "K_COPY",
  "K_PASTE",
  "K_FIND",

  // Numpad
  "K_NLCK",
  "K_KPSL",
  "K_KPAX",
  "K_KPMI",
  "K_KPPL",
  "K_KPEN",
  "K_KPDT",
  "K_KP_COMMA",
  "K_KP_EQUAL",
  "K_KP_EQUAL_AS400",
  "K_KP0",
  "K_KP1",
  "K_KP2",
  "K_KP3",
  "K_KP4",
  "K_KP5",
  "K_KP6",
  "K_KP7",
  "K_KP8",
  "K_KP9",

  // Intl
  "K_INT1",
  "K_INT2",
  "K_INT3",
  "K_INT4",
  "K_INT5",
  "K_INT6",
  "K_INT7",
  "K_INT8",
  "K_INT9",
  "K_LANG1",
  "K_LANG2",
  "K_LANG3",
  "K_LANG4",
  "K_LANG5",
  "K_LANG6",
  "K_LANG7",
  "K_LANG8",
  "K_LANG9",

  // System
  "K_POWER",
  "K_PWR",
  "K_SLEP",
  "K_WAKE",
  "K_ROLL_OVER",
  "K_POST_FAIL",
  "K_UNDEFINED",

  // Media
  "K_MUTE",
  "K_VOLU",
  "K_VOLD",
  "K_PLAY",
  "K_NEXT",
  "K_PREV",
  "K_MSTP",
  "K_MFFD",
  "K_MRWD",
  "K_EJCT",
  "K_MSEL",
  "K_MAIL",
  "K_CALC",
  "K_MYCM",
  "K_WSCH",
  "K_WHOM",
  "K_WBAK",
  "K_WFWD",
  "K_WSTP",
  "K_WREF",
  "K_WFAV",

  // Mouse
  "K_MS_U",
  "K_MS_D",
  "K_MS_L",
  "K_MS_R",
  "K_BTN1",
  "K_BTN2",
  "K_BTN3",
  "K_BTN4",
  "K_BTN5",
  "K_WH_U",
  "K_WH_D",
  "K_WH_L",
  "K_WH_R",
  "K_ACL0",
  "K_ACL1",
  "K_ACL2",

  // Custom Layer
  "K_LYRUP",
  "K_LYRDWN",
];
