// Словарь для отображения знаков на кнопках (маппинг)
const DISPLAY_MAP = {
  // Базовые и прозрачность
  K_TRNS: "▽",
  K_NO: "✕",

  // Алфавит и цифры
  K_A: "A", K_B: "B", K_C: "C", K_D: "D", K_E: "E", K_F: "F", K_G: "G",
  K_H: "H", K_I: "I", K_J: "J", K_K: "K", K_L: "L", K_M: "M", K_N: "N",
  K_O: "O", K_P: "P", K_Q: "Q", K_R: "R", K_S: "S", K_T: "T", K_U: "U",
  K_V: "V", K_W: "W", K_X: "X", K_Y: "Y", K_Z: "Z",
  K_1: "1", K_2: "2", K_3: "3", K_4: "4", K_5: "5",
  K_6: "6", K_7: "7", K_8: "8", K_9: "9", K_0: "0",

  // Пунктуация и системные
  K_ESC: "ESC",
  K_TAB: "↹",
  K_SPC: "␣",
  K_ENT: "↵",
  K_BSPC: "⌫",
  K_MINS: "-",
  K_EQL: "=",
  K_LBRC: "[",
  K_RBRC: "]",
  K_BSLS: "\\",
  K_SCLN: ";",
  K_QUOT: "'",
  K_GRV: "`",
  K_COMM: ",",
  K_DOT: ".",
  K_SLSH: "/",
  K_CAPS: "CAPS",

  // Модификаторы
  K_LCTRL: "LCTRL",
  K_RCTRL: "RCTRL",
  MOD_LCTRL: "LCTRL",
  MOD_RCTRL: "RCTRL",
  K_LSHIFT: "LSHIFT",
  K_RSHIFT: "RSHIFT",
  MOD_LSHIFT: "LSHIFT",
  MOD_RSHIFT: "RSHIFT",
  K_LALT: "LALT",
  K_RALT: "RALT",
  MOD_LALT: "LALT",
  MOD_RALT: "RALT",
  K_LGUI: "LGUI",
  K_RGUI: "RGUI",
  MOD_LGUI: "LGUI",
  MOD_RGUI: "RGUI",
  MOD_HYPER: "HYP",

  // Навигация, редактирование и F-кнопки
  K_LEFT: "←",
  K_RIGHT: "→",
  K_UP: "↑",
  K_DOWN: "↓",
  K_INS: "INS",
  K_DEL: "DEL",
  K_HOME: "HOME",
  K_END: "END",
  K_PGUP: "PGUP",
  K_PGDN: "PGDN",
  K_PSCR: "PRTSC",
  K_SCRL: "SCRLK",
  K_PAUS: "PAUSE",
  K_MENU: "MENU",
  K_F1: "F1", K_F2: "F2", K_F3: "F3", K_F4: "F4", K_F5: "F5", K_F6: "F6",
  K_F7: "F7", K_F8: "F8", K_F9: "F9", K_F10: "F10", K_F11: "F11", K_F12: "F12",
  K_F13: "F13", K_F14: "F14", K_F15: "F15", K_F16: "F16", K_F17: "F17", K_F18: "F18",
  K_F19: "F19", K_F20: "F20", K_F21: "F21", K_F22: "F22", K_F23: "F23", K_F24: "F24",
  K_EXECUTE: "EXEC",
  K_HELP: "HELP",
  K_MENU_KB: "MENU",
  K_SELECT: "SEL",
  K_STOP_KB: "STOP",
  K_AGAIN: "AGAIN",
  K_UNDO: "UNDO",
  K_CUT: "CUT",
  K_COPY: "COPY",
  K_PASTE: "PASTE",
  K_FIND: "FIND",

  // Numpad
  K_NLCK: "NUM",
  K_KP_SLASH: "NUM /",
  K_KP_ASTERISK: "NUM *",
  K_KP_MINUS: "NUM -",
  K_KP_PLUS: "NUM +",
  K_KP_ENTER: "NUM ↵",
  K_KP_DOT: "NUM .",
  K_KP_EQUAL: "NUM =",
  K_KP0: "N0", K_KP1: "N1", K_KP2: "N2", K_KP3: "N3", K_KP4: "N4",
  K_KP5: "N5", K_KP6: "N6", K_KP7: "N7", K_KP8: "N8", K_KP9: "N9",

  // Consumer Media Keys
  K_MUTE: "MUTE",
  K_VOLU: "VOL+",
  K_VOLD: "VOL-",
  K_MPLY: "PLAY",
  K_MNXT: "NEXT",
  K_MPRV: "PREV",
  K_MSTP: "STOP",
  K_BRIU: "BRI+",
  K_BRID: "BRI-",
  K_CALC: "CALC",
  K_MYCM: "PC",

  // System & Bootloader
  K_BOOTLOADER: "BOOT"
};
